### ISSUE TITLE
Confused by the first registration of schema

### ISSUE THREAD

**Issue by Annyxh** [rob3000/nestjs-kafka#38]
Sorry, my understanding may be wrong.
I found we only have getSchemaIds in KafkaAvroRequestSerializer.
Does that mean we don't support registering these schema to avro by nestJs app?

**Comment by rob3000** [comment]
Hey @Annyxh , That's correct, currently the expectation is that the AVRO schema is defined and already created in Schema Registry. There is a test that programmatically sends an avro schema to SR here: https://github.com/rob3000/nestjs-kafka/blob/master/test/utils.ts#L15 which you could look to do on your service start? Otherwise happy to accept PRs/suggestions for it.

**Comment by Annyxh** [comment]
Thanks & that's a good example

**Comment by rob3000** [comment]
No problems @Annyxh. Are you happy if i close this issue?
